Tushar leetcode
pradhan1234/leetcode pull request #32
Opened 2019-05-23 17:20 UTC by tushar8049

2019-05-23 19:37 UTC, pradhan1234 requested changes

2019-05-23 19:37 UTC, pradhan1234 commented on 0043. Multiply String/Solution.java
> +
Looks Great! Do add space time complexity of the solution.

2019-05-23 19:37 UTC, pradhan1234 commented on 0043. Multiply String/Solution.java
> +                d[i+1] += carry;    //Adding Cary forward String
typo here

2019-05-23 19:37 UTC, pradhan1234 commented on 0043. Multiply String/Solution.java
> +            result.insert(0, rem); // reminder inserted at the begining everytime because we are accessing it from the end and we don't wanna reverse it again after building the string.
remainder*

2019-05-23 19:37 UTC, pradhan1234 commented on 0043. Multiply String/Solution.java
> +        for(int i = 0; i < n1.length(); i++){
brief comment about what's going on here

2019-05-23 20:27 UTC, pradhan1234 approved these changes

2019-05-24 14:47 UTC, tushar8049 reviewed
@pradhan1234 Can you look into this!

2019-05-24 16:32 UTC, pradhan1234 requested changes

2019-05-24 16:32 UTC, pradhan1234 commented on 0232. Implementing Queue using Stack/MyQueue.java
> +
Looks Great, just nit picks.
Better to declare stack s1 and s2 above constructor and initialize them using the constructor.
you can consider moving new stack<>() inside constructor.

2019-05-24 16:32 UTC, pradhan1234 commented on 0232. Implementing Queue using Stack/MyQueue.java
> +
another small point
for comments over push, pop, peek and empty use one multiline comment to contain the comments

2019-05-24 16:57 UTC, pradhan1234 requested changes

2019-05-24 16:57 UTC, pradhan1234 commented on 0080. Remove Duplicates from Sorted Array II/Solution.java
> +
Space Time Complexity

2019-05-24 17:21 UTC, pradhan1234 approved these changes

2019-05-24 17:23 UTC, merged